### ISSUE TITLE
Pride-Yay Reaction

### ISSUE THREAD

**Issue by kareemman00** [CaliAlec/Forever-Thankful-On-FB#2]
The Server Still Accept Those Reactions As I Found Them In Too Much Posts
Also When I Send Requests With Changed reaction_type parameter i found that
1 = like 
2 = love 
3 = haha 
4 = unknown 
5 = unknown 
6 = unknown 
7 = wow 
8 = sad 
9 = angry 
10 until 15 = unknown
i hope we bring them back :"(

**Comment by azlkiniue** [comment]
how to do that? please let me know

**Comment by gpressutto5** [comment]
14 = 🔥 
15 = ✈️

**Comment by normaschneider** [comment]
10 = hein? 😳
but it doesn't work

**Comment by CaliAlec** [comment]
http://fortune.com/2018/07/31/airplane-reaction-facebook-news-feed/

Looks like Facebook's Android app accidentally released with the fire 🔥and airplane ✈️reacts, but it seems to be blocked from the server side now.
